version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db