version: '3'

services:
  taskloader:
    build: .
    container_name: taskloader
    command: uwsgi --socket :8001 --module djangoproj.wsgi --enable-threads
    volumes:
      - ./src:/src
      - ./src/static:/static
    environment:
      TZ: Asia/Tokyo
    expose:
      - "8001"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - taskloader