services:
  - type: web
    name: taskloader
    env: python
    region: singapore
    buildCommand: './build.sh'
    command: uwsgi --socket :8001 --module djangoproj.wsgi --enable-threads
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true