# Generated by Django 3.2 on 2022-02-18 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='individualconditions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='individualkeys',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='ユーザー'),
        ),
    ]
